# Site settings
title: Shiny Inbox
email: shinyinbox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Productivity hacks.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: shinyinbox
permalink: pretty
url: http://www.shinyinbox.com

# Build settings
markdown: kramdown