# Site settings
title: Shiny Inbox
email: shinyinbox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Productivity hacks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shinyinbox
pages_list:       
  About: '/about'
  Archivve: '/archive'
  Feed: '/atom.xml'

# Build settings
markdown: kramdown
