# Site settings
title: Shiny Inbox
email: shinyinbox@gmail.com
description: >
  Productivity hacks.
baseurl: ""
url: "http://www.shinyinbox.com"
twitter_username: shinyinbox
permalink: pretty

# Build settings
markdown: kramdown