# Site settings
title: Shiny Inbox
email: shinyinbox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Productivity hacks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.shinyinbox.com" # the base hostname & protocol for your site
twitter_username: shinyinbox

# Build settings
markdown: kramdown
